-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "editedAt" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "editedAt" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
